# Generated by Django 6.0 on 2025-12-26 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_direccionenvio_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccionenvio',
            options={'verbose_name': 'Dirección de Envío', 'verbose_name_plural': 'Direcciones de Envío'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_terminos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='alias',
            field=models.CharField(help_text='Ej: Casa, Oficina', max_length=50),
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='calle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='direccionenvio',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
